// 멤버 소개 데이터: bio와 spoonUrl에서 소개 문구 및 스푼라디오 링크를 관리합니다.
const members = [
 {name:'휴맨',image:'휴맨.png',role:'TEAM LEADER · 팀장',initial:'휴',bio:'OST의 팀장입니다. 팀의 방향을 함께 고민하고 멤버들과 협력하며 활동을 이끌어갑니다.',spoonUrl:'https://www.spooncast.net/kr/@y32979z?utm_source=spoon_share&utm_medium=referral&utm_campaign=profile_share&utm_content=10291412&utm_term=10291412&ts=1790537586219'},
 {name:'시아',image:'시아.png',role:'VICE LEADER · 부팀장',initial:'시',bio:'OST의 부팀장입니다. 팀장과 함께 팀 운영을 지원하고 멤버들의 활동을 연결합니다.',spoonUrl:'https://www.spooncast.net/kr/@sia1914?utm_source=spoon_share&utm_medium=referral&utm_campaign=profile_share&utm_content=2897340&utm_term=2897340&ts=1790537598675'},
 {name:'Lua',image:'Lua.png',role:'MEMBER · 멤버',initial:'L',bio:'OST의 멤버입니다. 자신만의 개성과 목소리로 팀의 활동에 함께합니다.',spoonUrl:'https://www.spooncast.net/kr/@x9pp364?utm_source=spoon_share&utm_medium=referral&utm_campaign=profile_share&utm_content=10385611&utm_term=10385611&ts=1790537573719'},
 {name:'민기',image:'민기.png',role:'MEMBER · 멤버',initial:'민',bio:'OST의 멤버입니다. 콘텐츠와 방송을 통해 팀의 이야기를 함께 만들어갑니다.',spoonUrl:'https://www.spooncast.net/kr/@mingi0811?utm_source=spoon_share&utm_medium=referral&utm_campaign=profile_share&utm_content=9419028&utm_term=9419028&ts=1790537552879'},
 {name:'유감',image:'유감.png',role:'MEMBER · 멤버',initial:'유',bio:'OST의 멤버입니다. 각자의 색을 존중하며 팀의 다양한 활동에 참여합니다.',spoonUrl:'https://www.spooncast.net/kr/@yougam?utm_source=spoon_share&utm_medium=referral&utm_campaign=profile_share&utm_content=10220848&utm_term=10220848&ts=1790537609361'},
 {name:'우유',image:'우유.png',role:'MEMBER · 멤버',initial:'우',bio:'OST의 멤버입니다. 함께하는 방송과 콘텐츠에 즐거움을 더합니다.',spoonUrl:'https://www.spooncast.net/kr/@2dollar?utm_source=spoon_share&utm_medium=referral&utm_campaign=profile_share&utm_content=9030041&utm_term=9030041&ts=1790537620981'},
 {name:'이겸',image:'이겸.png',role:'MEMBER · 멤버',initial:'겸',bio:'OST의 멤버입니다. 팀원들과 함께 새로운 순간과 이야기를 만들어갑니다.',spoonUrl:'https://www.spooncast.net/kr/@bourbon_2003?utm_source=spoon_share&utm_medium=referral&utm_campaign=profile_share&utm_content=2455446&utm_term=2455446&ts=1790537631259'}
];
const grid=document.getElementById('teamGrid');
members.forEach((m,i)=>{const b=document.createElement('button');b.className='member-card';b.type='button';b.innerHTML=`<div class="avatar"><img src="${m.image}" alt="${m.name} 프로필 일러스트" loading="lazy"></div><div class="member-role">${m.role}</div><div class="member-name">${m.name}</div><div class="member-hint">VIEW PROFILE</div><span class="card-arrow">↗</span>`;b.addEventListener('click',()=>openProfile(m));grid.appendChild(b)});
const modal=document.getElementById('profileModal');function openProfile(m){const avatar=document.getElementById('modalAvatar');avatar.innerHTML=`<img src="${m.image}" alt="${m.name} 프로필 일러스트">`;document.getElementById('modalRole').textContent=m.role;document.getElementById('modalName').textContent=m.name;document.getElementById('modalBio').textContent=m.bio;const link=document.getElementById('modalLink');if(m.spoonUrl){link.href=m.spoonUrl;link.hidden=false}else{link.hidden=true}modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeProfile(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.style.overflow=''}modal.querySelectorAll('[data-close]').forEach(el=>el.addEventListener('click',closeProfile));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeProfile()});
const toggle=document.querySelector('.menu-toggle'),nav=document.getElementById('nav');toggle.addEventListener('click',()=>{const opened=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(opened))});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));document.getElementById('year').textContent=new Date().getFullYear();
